blank_issues_enabled: false

contact_links:
    - name: Ask
      url: https://github.com/doronbrayer/shuffrand/discussions
      about: Ask questions and get help from the community

    - name: Security Vulnerability Report
      url: https://github.com/doronbrayer/shuffrand/security/policy
      about: Please report security vulnerabilities responsibly.

issue_templates:
    - name: Report
      description: Report a problem or unexpected behavior
      template: bug_report.md

    - name: Request
      description: Suggest a new idea or enhancement
      template: feature_request.md
