blank_issues_enabled: false

contact_links:
    - name: Discuss
      url: https://github.com/DoronBrayer/monorand/discussions
      about: Use 'Discussions' to connect with our community
issue_templates:
    - name: Report
      description: Report a defect or unexpected behavior
      template: bug_report.md

    - name: Request
      description: Request an enhancement or feature
      template: feature_request.md
