# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
    - name: Ask a question
      url: https://github.com/doronbrayer/shuffrand/discussions
      about: Ask questions and get help from the community.
    - name: Security Vulnerability Report
      url: https://github.com/doronbrayer/shuffrand/security/policy
      about: Please report security vulnerabilities responsibly.
