blank_issues_enabled: false

contact_links:
    - name: Ask
      url: https://github.com/doronbrayer/shuffrand/discussions
      about: Get help for the community

issue_templates:
    - name: Report
      description: Report a problem or unexpected behavior
      template: bug_report.md

    - name: Request
      description: Suggest a new idea or enhancement
      template: feature_request.md
